export const FETCH_USERS = 'FETCH_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const DEL_USER = 'DEL_USER'
export const CHANGE_AUTH = 'CHANGE_AUTH'
export const SET_MODAL = 'SET_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CREATE_USER = 'CREATE_USER'